name: 'Halfass BackWards & UpSideDown'
favicon: null
layout_spectrum: 0.1790613776538521
typography_spectrum: 0.7706611368339509
title: '95 & SUNNY--!!--HELLO--Pay Attention??-!!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4c7ba7'
    - '#7cadce'
    - '#191411'
    - '#fffdff'
    - '#f2ab73'
  brandStrength: 1
  lightness: 0.9382829954847693
  saturation: 1
  rhythmicContrast: 0.484535297146067
purpose: []
